# Generated by Django 4.0.6 on 2022-09-13 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='composer',
            name='portrait',
            field=models.URLField(blank=True, null=True),
        ),
    ]
