# Generated by Django 4.0.6 on 2022-09-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composers', '0005_alter_composer_epoch'),
    ]

    operations = [
        migrations.AddField(
            model_name='epoch',
            name='epoch_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
