# Generated by Django 4.0.6 on 2022-09-19 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('composers', '0007_genre_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='composer',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='genre_composers', to='composers.genre'),
        ),
        migrations.AddField(
            model_name='work',
            name='composer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='composer_works', to='composers.composer'),
        ),
        migrations.AlterField(
            model_name='work',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='genre_works', to='composers.genre'),
        ),
    ]
