# Generated by Django 4.0.6 on 2022-09-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composers', '0011_rename_genre_composer_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composer',
            name='death',
            field=models.DateField(blank=True, null=True),
        ),
    ]
