# Generated by Django 4.0.6 on 2022-09-27 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('composers', '0012_alter_composer_death'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='work_id',
        ),
    ]
