# Generated by Django 4.0.6 on 2022-09-29 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('composers', '0013_remove_work_work_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epoch',
            name='epoch_id',
        ),
    ]
