# Generated by Django 4.0.6 on 2022-09-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composers', '0014_remove_epoch_epoch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(blank='true', related_name='liked_by', to='composers.work'),
        ),
    ]
