# Generated by Django 4.0.6 on 2022-10-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composers', '0015_user_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='composer',
            name='name',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
